# Generated by Django 3.0.4 on 2020-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingprofile',
            options={'verbose_name': 'Billing Profile'},
        ),
        migrations.RemoveField(
            model_name='billingprofile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
