# Generated by Django 3.0.4 on 2020-03-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20200314_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='updtated_timestamp',
            new_name='updated_timestamp',
        ),
    ]
