# Generated by Django 3.0.4 on 2020-03-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
