# Generated by Django 3.0.4 on 2020-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0013_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
