# Generated by Django 3.0.4 on 2020-03-13 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0014_cart_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount_amount',
        ),
    ]
