# Generated by Django 3.0.4 on 2020-03-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_remove_cart_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Discount Amount'),
        ),
    ]
