# Generated by Django 3.0.4 on 2020-03-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_auto_20200308_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('products', models.ManyToManyField(blank=True, to='products.Product')),
            ],
        ),
    ]
