# Generated by Django 3.0.4 on 2020-03-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200318_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestemail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
