# Generated by Django 3.0.4 on 2020-03-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_total',
            new_name='delivery_total',
        ),
    ]
