# Generated by Django 3.0.4 on 2020-03-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200313_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
