# Generated by Django 3.0.4 on 2020-03-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.TextField(max_length=150, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Price')),
            ],
        ),
    ]
