# Generated by Django 3.0.4 on 2020-03-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('V', 'Vegetable'), ('F', 'Fruit')], default='V', max_length=1),
        ),
    ]
