# Generated by Django 3.0.4 on 2020-03-07 17:34

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200307_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5, verbose_name='Price after discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=products.models.IntegerRangeField(blank=True, null=True, verbose_name='Discount for Sale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
    ]
