# Generated by Django 3.0.4 on 2020-03-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200307_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'), max_digits=5, null=True, verbose_name='Price after discount'),
        ),
    ]
