# Generated by Django 3.0.4 on 2020-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200307_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
    ]
