# Generated by Django 3.0.4 on 2020-03-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200308_0153'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='title',
        # ),
    ]
